apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vedhansri-prod
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP # ఇది కూడా ప్రైవేట్‌గానే ఉంటుంది, ఇన్గ్రెస్ ద్వారానే బయటికి కనిపిస్తుంది