apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: vedhansri-prod
type: Opaque
data:
  # ఇక్కడ మనం వేరియబుల్స్ వాడుతున్నాం
  DB_PASSWORD: ${DB_PASSWORD_BASE64}
  DB_USERNAME: ${DB_USERNAME_BASE64}