apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: vedhansri-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking-app
        image: your-docker-username/booking-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_HOST
          value: "vedhansri-production-db.xyz.ap-south-1.rds.amazonaws.com"
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):5432/booking_db"